import { Injectable } from '@nestjs/common';

export interface Product {
    id: number;
    name: string;
    price: number;
    description: string;
}

@Injectable()
export class ProductsService {
    private products: Product[] = [];
    private idCounter = 1;

    // When you're creating a new product, you typically don't know its id yet. 
    // The id is often generated by the database or the backend system.
    // interface ProductWithoutId {
    //     name: string;
    //     price: number;
    //     description?: string;
    // }
    create(product: Omit<Product, 'id'>): Product {
        const newProduct = {id: this.idCounter++, ...product};
        this.products.push(newProduct);
        return newProduct;
    }

    findAll(): Product[] {
        return this.products;
    }

    findOne(id: number): Product | undefined {
        return this.products.find((p) => p.id === id);
    }

    update(id: number, update: Partial<Product>): Product | null {
        const index = this.products.findIndex((p) => p.id === id);
        if(index === -1) return null;
        this.products[index] = {...this.products[index], ...update};
        return this.products[index];
    }

    delete(id: number): boolean {
        const index = this.products.findIndex((p) => p.id === id);
        if(index === -1) return false;
        this.products.splice(index, 1);
        return true;
    }
}
